Add new SSM document to update the Amazon Linux OS

diff --git a/aws_marketplace_cloudformation.yaml b/aws_marketplace_cloudformation.yaml
--- a/aws_marketplace_cloudformation.yaml
+++ b/aws_marketplace_cloudformation.yaml
@@ -493,6 +493,29 @@ Resources:
                   fi
                 - 'echo "System packages and Docker updated successfully!"'
 
+  # New SSM document to update the Amazon Linux OS
+  UpdateAWSLinuxOSDocument:
+    Type: AWS::SSM::Document
+    Properties:
+      DocumentType: Command
+      Content:
+        schemaVersion: '2.2'
+        description: "Update the system OS"
+        mainSteps:
+          - action: aws:runShellScript
+            name: updateAWSLinux
+            inputs:
+              runCommand:
+                - 'echo "Updating Amazon Linux OS to the latest release version..."'
+                - |
+                  if ! sudo dnf upgrade --releasever=latest -y 2>&1; then
+                    echo "Failed to update Amazon Linux OS to the latest release version"
+                    echo "Output of dnf upgrade:"
+                    sudo dnf upgrade --releasever=latest -y 2>&1
+                    exit 1
+                  fi
+                - 'echo "Amazon Linux OS updated successfully to the latest release version!"'
+
 Outputs:
   PublicIP:
     Description: The Public IP Address of the newly created EC2 instance
