Update script to work. Testing complete

diff --git a/aws_marketplace_cloudformation.yaml b/aws_marketplace_cloudformation.yaml
--- a/aws_marketplace_cloudformation.yaml
+++ b/aws_marketplace_cloudformation.yaml
@@ -473,7 +473,7 @@ Resources:
       DocumentType: Command
       Content:
         schemaVersion: '2.2'
-        description: "Update system packages and Docker"
+        description: "Update system packages and Docker (DOCKER AND OPENREMOTE WILL BE RESTARTED ONCE COMPLETE)"
         mainSteps:
           - action: aws:runShellScript
             name: updatePackages
@@ -500,21 +500,23 @@ Resources:
       DocumentType: Command
       Content:
         schemaVersion: '2.2'
-        description: "Update the system OS"
+        description: "Update the system OS (EC2 INSTANCE WILL REBOOT AUTOMATICALLY ONCE COMPLETE)"
         mainSteps:
           - action: aws:runShellScript
             name: updateAWSLinux
             inputs:
               runCommand:
-                - 'echo "Updating Amazon Linux OS to the latest release version..."'
+                - 'echo "Starting Amazon Linux OS update..."'
                 - |
-                  if ! sudo dnf upgrade --releasever=latest -y 2>&1; then
-                    echo "Failed to update Amazon Linux OS to the latest release version"
-                    echo "Output of dnf upgrade:"
-                    sudo dnf upgrade --releasever=latest -y 2>&1
+                  if ! sudo dnf upgrade --releasever=latest -y --quiet 2>/dev/null; then
+                    echo "Error: Update failed. Full error log:"
+                    sudo dnf upgrade --releasever=latest -y
                     exit 1
                   fi
-                - 'echo "Amazon Linux OS updated successfully to the latest release version!"'
+                - 'sudo dnf clean all --quiet'
+                - 'echo "Rebooting EC2 instance"'
+                - "sudo reboot now"
+                - 'echo "Amazon Linux OS update completed successfully"'
 
 Outputs:
   PublicIP:
